# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Install dependencies
        run: |
          zip -r dce-id-process-csv-to-sqs-lambda.zip dce-id-process-csv-to-sqs-lambda
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dce-id-process-csv-to-sqs-lambda.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
